name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build lablink-client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[dev]

      - name: Build package
        run: |
          python -m build
          twine check dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lablink-client-dist
          path: dist/
          retention-days: 1

  prepare:
    name: Create Serivce Account
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "vmassign-dev"
          workload_identity_provider: "projects/446967198037/locations/global/workloadIdentityPools/github-actions/providers/my-repo"

      - name: Create a Temporary Service Account
        id: create
        run: |
          gcloud iam service-accounts create "github-actions-testing" \
            --description="Temporary Service Account for GitHub Actions" \
            --display-name="GitHub Actions Service Account"

      - name: Grant the Service Account the necessary permissions
        if: ${{ steps.create.outputs.status }} == "success"
        id: assign
        run: |
          gcloud projects add-iam-policy-binding vmassign-dev \
            --member="serviceAccount:github-actions-testing@vmassign-dev.iam.gserviceaccount.com" \
            --role="roles/iam.serviceAccountTokenCreator"

          gcloud iam service-accounts add-iam-policy-binding github-actions-testing@vmassign-dev.iam.gserviceaccount.com \
            --member="serviceAccount:github-actions-testing@vmassign-dev.iam.gserviceaccount.com" \
            --role="roles/iam.serviceAccountUser"

          gcloud projects add-iam-policy-binding vmassign-dev \
            --member="serviceAccount:github-actions-testing@vmassign-dev.iam.gserviceaccount.com" \
            --role="roles/spanner.admin"


          gcloud projects add-iam-policy-binding vmassign-dev \
            --member="serviceAccount:github-actions-testing@vmassign-dev.iam.gserviceaccount.com" \
            --role="roles/iam.serviceAccountAdmin"

      - name: Impersonate the Service Account
        if: ${{ steps.assign.outputs.status }} == "success"
        run: |
          sleep 10
          gcloud iam service-accounts add-iam-policy-binding github-actions-testing@vmassign-dev.iam.gserviceaccount.com \
            --role=roles/iam.workloadIdentityUser \
            --member="principalSet://iam.googleapis.com/projects/446967198037/locations/global/workloadIdentityPools/github-actions/attribute.repository/talmolab/cosyne_vm"

      - name: Check Service Account
        if: ${{ steps.assign.outputs.status }} == "success"
        run: |
          gcloud iam service-accounts get-iam-policy github-actions-testing@vmassign-dev.iam.gserviceaccount.com
          gcloud projects get-iam-policy vmassign-dev --flatten="bindings[].members" --format="table(bindings.role, bindings.members)" | grep "github-actions-testing"

  tests:
    name: Test lablink-client
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "vmassign-dev"
          workload_identity_provider: "projects/446967198037/locations/global/workloadIdentityPools/github-actions/providers/my-repo"
          service_account: "github-actions-testing@vmassign-dev.iam.gserviceaccount.com"

      - name: Wait
        run: sleep 10

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.4

      - name: Terraform Init
        run: |
          terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: |
          terraform validate -no-color
        working-directory: ./terraform

      - name: Terraform Plan
        run: |
          terraform plan -no-color
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -no-color
        working-directory: ./terraform

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Change Directory to Project Root
        run: |
          cd ../

      - name: Debug Current Directory
        run: |
          pwd

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lablink-client-dist
          path: dist/

      - name: List files
        run: |
          ls dist/

      - name: Install package from artifact
        run: |
          WHL=$(ls dist/*.whl)
          pip install "$WHL[dev]"

      - name: Print installed packages
        run: |
          pip list

      - name: Run tests
        run: |
          pytest tests/

      - name: Clean up Terraform resources
        if: always()
        run: |
          terraform plan -destroy -no-color
          terraform destroy -auto-approve -no-color
        working-directory: ./terraform

  cleanup:
    name: Clean up Service Account
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "vmassign-dev"
          workload_identity_provider: "projects/446967198037/locations/global/workloadIdentityPools/github-actions/providers/my-repo"

      - name: Check Roles
        run: |
          gcloud projects get-iam-policy vmassign-dev --format=json | jq '.bindings[] | select(.members[] | contains("github-actions-testing@vmassign-dev.iam.gserviceaccount.com"))'

      - name: Clean up Service Account
        run: |
          gcloud projects remove-iam-policy-binding vmassign-dev \
            --member="serviceAccount:github-actions-testing@vmassign-dev.iam.gserviceaccount.com" \
            --role="roles/iam.serviceAccountTokenCreator"

          gcloud projects remove-iam-policy-binding vmassign-dev \
            --member="serviceAccount:github-actions-testing@vmassign-dev.iam.gserviceaccount.com" \
            --role="roles/spanner.admin"

          gcloud iam service-accounts remove-iam-policy-binding github-actions@vmassign-dev.iam.gserviceaccount.com \
            --member="principalSet://iam.googleapis.com/projects/446967198037/locations/global/workforcePools/github-actions/attribute.repository/talmolab/cosyne_vm" \
            --role="roles/iam.workloadIdentityUser"

      - name: Delete Service Account
        if: always()
        run: |
          gcloud iam service-accounts delete "github-actions-testing@vmassign-dev.iam.gserviceaccount.com" --quiet
