name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build lablink-client
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --editable .[dev]

    - name: Build package
      run: |
        python -m build
        twine check dist/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lablink-client-dist
        path: dist/
        retention-days: 1

  tests:
    name: Test lablink-client
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: lablink-client-dist
        path: dist/

    - name: List files
      run: |
        ls dist/

    - name: Install package from artifact
      run: |
        WHL=$(ls dist/*.whl)
        pip install "$WHL[dev]"

    - name: Print installed packages
      run: |
        pip list

    - name: Run tests
      run: |
        pytest tests/
