name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build lablink-client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[dev]

      - name: Build package
        run: |
          python -m build
          twine check dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lablink-client-dist
          path: dist/
          retention-days: 1

  terraform:
    name: Terraform Setup
    runs-on: ubuntu-latest
    needs: build

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "vmassign-dev"
          service_account: "service-account-admin@vmassign-dev.iam.gserviceaccount.com"
          workload_identity_provider: "projects/446967198037/locations/global/workloadIdentityPools/github-actions/providers/my-repo"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color

  tests:
    name: Test lablink-client
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "vmassign-dev"
          service_account: "service-account-admin@vmassign-dev.iam.gserviceaccount.com"
          workload_identity_provider: "projects/446967198037/locations/global/workloadIdentityPools/github-actions/providers/my-repo"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lablink-client-dist
          path: dist/

      - name: List files
        run: |
          ls dist/

      - name: Install package from artifact
        run: |
          WHL=$(ls dist/*.whl)
          pip install "$WHL[dev]"

      - name: Print installed packages
        run: |
          pip list

      - name: Run tests
        run: |
          pytest tests/
